
import json
from agent_core.agent_logger import log_agent_run, log_error
from agent_core.global_agent_memory import get_context, store_memory
from agent_core.downstream_formatter import tag_downstream_fields
from agent_core.trust_explainability import generate_why_this_output_summary
from agent_core.timing_utils import track_time
from agent_core.prompt_builder import build_prompt_from_context
from agent_core.llm_client import call_llm_model
from agent_core.self_learning import get_prompt_considerations, learn_from_feedback

@track_time("role_ladder_inference")
async def infer_ladder_position(user_id, session_id):
    agent_name = "role_ladder_agent"
    subtask_id = "ladder_inference"

    try:
        # Get context directly from memory store
        from agent_core.global_agent_memory import _memory_store as memory_store
        context = memory_store.get((user_id, session_id), {})
        print("\n=== Context Passed to Prompt Builder ===")
        print(json.dumps(context, indent=2))

        # Default considerations for role ladder analysis
        considerations = [
            "Avoid over-indexing on inflated titles",
            "Use company type and team size to normalize title",
            "Favor realism over optimism",
            "Consider years of experience as a key signal"
        ]
        print("\n=== Considerations Passed to Prompt Builder ===")
        print(json.dumps(considerations, indent=2))
        
        print("\n=== Calling Prompt Builder ===")
        prompt_package = build_prompt_from_context(
            task="ladder_inference",
            agent_role="You are a senior career strategist with expertise in org-level leveling and promotion readiness.",
            task_instruction="Infer the user's true position on a normalized IC/managerial ladder and the next logical step.",
            user_context=context,
            memory_context=context,
            considerations=[
                "Avoid over-indexing on inflated titles",
                "Use company type and team size to normalize title",
                "Favor realism over optimism"
            ],
            output_format="""
            {
                "inferred_ladder_level": "Current normalized level (IC1-IC5 or M1-M3)",
                "next_logical_level": "Next realistic career step",
                "progression_velocity": "Slow/Moderate/Fast based on YoE and scope",
                "ladder_alignment_flag": "Title/Experience/Scope based",
                "normalization_explanation": "Brief explanation of level assessment",
                "management_signal": "IC or Management track signal"
            }
            """
        )

        print("\n=== Prompt Builder Output ===")
        print(json.dumps(prompt_package, indent=2))
        
        if not prompt_package.get("prompt"):
            raise ValueError("No prompt generated by prompt builder")
            
        llm_response = call_llm_model(prompt_package["prompt"], model_params={"temperature": 0.2})

        llm_response = call_llm_model(
            prompt_package["prompt"], 
            model_params={"temperature": 0.2}
        )
        result = json.loads(llm_response)

        required_fields = [
            "inferred_ladder_level", "next_logical_level",
            "progression_velocity", "ladder_alignment_flag", 
            "normalization_explanation", "management_signal"
        ]
        for field in required_fields:
            if field not in result:
                raise ValueError(f"Missing required field: {field}")

        tagged_output = tag_downstream_fields(result)

        await store_memory(
            agent_name=agent_name,
            user_id=user_id,
            session_id=session_id,
            subtask_id=subtask_id,
            function="inference_and_mapping",
            input_fields=context,
            output_fields=tagged_output
        )

        # Log successful run
        learn_from_feedback(
            agent_name,
            user_id,
            input_fields=context,
            signal=True,
            payload={
                "input_context": context,
                "output": result,
                "considerations_used": considerations
            }
        )

        log_agent_run(agent_name, context, tagged_output)
        generate_why_this_output_summary(
            agent_name=agent_name,
            input_summary=str(context),
            rules_used="Level normalization using org-type + domain + aspiration",
            model_confidence="high"
        )

        return result

    except Exception as e:
        log_error(agent_name, f"Role ladder inference failed: {str(e)}")
        
        # Log failure
        learn_from_feedback(
            agent_name,
            user_id,
            input_fields={"error": str(e)},
            signal=False,
            payload={
                "error": str(e),
                "input_context": context if 'context' in locals() else None
            }
        )
        
        return {
            "inferred_ladder_level": "IC2",
            "next_logical_level": "IC3", 
            "progression_velocity": "Moderate",
            "ladder_alignment_flag": "Experience-Based",
            "normalization_explanation": "Fallback output due to exception",
            "management_signal": "IC"
        }
